# Site metadata
title: Kira's Dev Logs
email: kirathepansexualpixie@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A collection of my development logs.
# baseurl: ""
baseurl: "/devlogs"
url: "https://queenkirathepansexualpixie.github.io"
github_username:  QueenKiraThePansexualPixie

# Collections
collections:
  projects:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
